<img src="../img/Recurso.png" width="500">

## Actividad 2
## Nombre: Steven Chuiza
### Fecha: 05/05/2026

In [6]:
from sklearn import preprocessing
import numpy as np

In [7]:
# Carga de datos.
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [8]:
# Limpieza de datos: estandarización.
standardizer = preprocessing.StandardScaler()

# Estandarizamos los datos de entrenamiento
X_train_std=standardizer.fit_transform(X_train)
print(X_train_std)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [9]:
X_train_2 = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [10]:
# Aplicamos los métodos "fit" y "transform" por separado
f=preprocessing.StandardScaler()
f=f.fit(X_train)
X_train_2_std = f.transform(X_train_2)
print(X_train_2_std)


[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [11]:
# Comprobar si las matrices estandarizadas son iguales
# ???

In [13]:
# Imprimir True si ambas matrices analizadas son prácticamente iguales
son_iguales = np.allclose(X_train_std, X_train_2_std)
print(f"¿Son las matrices iguales?: {son_iguales}")

¿Son las matrices iguales?: True
